genesis_time = "2022-02-15T18:38:52+00:00"

[parameters]
min_num_of_blocks = 10
min_duration = 60

[pos_params]
max_validator_slots = 128
pipeline_len = 2
unbonding_len = 3
votes_per_token = 10
block_proposer_reward = 100
block_vote_reward = 1
duplicate_vote_slash_rate = 500
light_client_attack_slash_rate = 500

[validator.validator-1]
tokens = 200000
non_staked_balance = 1000000000000
validator_vp = "vp_user"
staking_reward_vp = "vp_user"
net_address = "10.0.0.10:26656"
matchmaker_account = "matchmaker"
matchmaker_code = "wasm/mm_token_exch.wasm"
matchmaker_tx = "wasm/tx_from_intent.wasm"

[validator.validator-2]
tokens = 200000
non_staked_balance = 1000000000000
validator_vp = "vp_user"
staking_reward_vp = "vp_user"
net_address = "10.0.0.20:26656"

[validator.validator-3]
tokens = 200000
non_staked_balance = 1000000000000
validator_vp = "vp_user"
staking_reward_vp = "vp_user"
net_address = "10.0.0.30:26656"

[validator.validator-4]
tokens = 200000
non_staked_balance = 1000000000000
validator_vp = "vp_user"
staking_reward_vp = "vp_user"
net_address = "10.0.0.40:26656"

[token.xan]
address = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
vp = "vp_token"

[token.btc]
address = "atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp"
vp = "vp_token"

[token.eth]
address = "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p"
vp = "vp_token"

[token.dot]
address = "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn"
vp = "vp_token"

[token.schnitzel]
address = "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"
vp = "vp_token"

[token.apfel]
address = "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9"
vp = "vp_token"

[token.kartoffel]
address = "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90"
public_key = ""
vp = "vp_token"

[established.matchmaker]
vp = "vp_user"

[established.faucet]
address = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
vp = "vp_testnet_faucet"

[wasm.vp_user]
filename = "vp_user.wasm"
sha256 = "73bbcf99b00b481b9cc5bac1d5a80a1647f3a30fd7de44b25bd4acfbaf6802df"

[wasm.vp_token]
filename = "vp_token.wasm"
sha256 = "9c83578e4a7c8839f87ed1d5efa676b2c0e40ce52832ca2a0b044955f6355e0b"

[wasm.vp_testnet_faucet]
filename = "vp_testnet_faucet.wasm"
sha256 = "6ef0f5ab15a7ce6b7352490524378f7160d0fb3050b7295e8d7f64cf6f4ea03f"

[token.xan.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.btc.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.eth.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.dot.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.schnitzel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.apfel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.kartoffel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854
